module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    fontFamily: {
      sans: [
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        '"Segoe UI"',
        'Roboto',
        '"Helvetica Neue"',
        'Arial',
        '"Noto Sans"',
        'sans-serif',
        '"Apple Color Emoji"',
        '"Segoe UI Emoji"',
        '"Segoe UI Symbol"',
        '"Noto Color Emoji"',
      ],
      serif: ['ui-serif', 'Georgia', 'Cambria', '"Times New Roman"', 'Times', 'serif'],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        '"Liberation Mono"',
        '"Courier New"',
        'monospace',
      ],
      default: ['Rubik', 'sans-serif'],
    },
    extend: {
      colors: {
        moderate_blue: '#5457b6',
        soft_red: '#ed6468',
        light_grayish_blue: '#c3c4ef',
        pale_red: '#ffb8bb',
        dark_blue: '#324152',
        grayish_blue: '#67727e',
        light_gray: '#eaecf1',
        very_light_gray: '#f5f6fa',
        white: '#ffffff',
      },
    },
  },
  plugins: [],
};
